### PR TITLE
fix: Add null checks to ScaleAdjusterPreview

### LINKED ISSUE #1115: SkinnedMeshRendererにnullのボーンが含まれている時にScaleAdjusterがエラーを出す
https://github.com/bdunderscore/modular-avatar/blob/1163fac2e7da199f998264200faf944eab5954ee/Editor/ScaleAdjuster/ScaleAdjusterPreview.cs#L325  
ここのnullチェックが抜けてそうです

### PR DESCRIPTION
**Pull request by Rerigferl**
Closes #1115

### CODE REVIEW

File: Editor/ScaleAdjuster/ScaleAdjusterPreview.cs [hunk 1]
```diff
@@ -322,7 +322,7 @@ public void OnFrame(Renderer original, Renderer proxy)
 
             var rootBone = _finalBonesMap.TryGetValue(smr.rootBone, out var newRootBone) ? newRootBone : smr.rootBone;
             smr.rootBone = rootBone;
-            smr.bones = smr.bones.Select(b => _finalBonesMap.GetValueOrDefault(b, b)).ToArray();
+            smr.bones = smr.bones.Select(b => b is null ? null : _finalBonesMap.GetValueOrDefault(b, b)).ToArray();
```
Comment (bdunderscore) [inline Editor/ScaleAdjuster/ScaleAdjusterPreview.cs:325]: Should this use `== null` to check for Unity destroyed-on-native-side objects as well?
